{% set version = "0.1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gridtext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gridtext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gridtext/gridtext_{{ version }}.tar.gz
  sha256: 6d98716461f8574b4c8f72c6b2163b92bb394e60e247e19f42912b871616f138

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-curl                       # [build_platform != target_platform]
    - r-jpeg                       # [build_platform != target_platform]
    - r-markdown                   # [build_platform != target_platform]
    - r-png                        # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-stringr                    # [build_platform != target_platform]
    - r-xml2                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-curl
    - r-jpeg
    - r-markdown
    - r-png
    - r-rlang
    - r-stringr
    - r-xml2
  run:
    - r-base
    - r-rcpp
    - r-curl
    - r-jpeg
    - r-markdown
    - r-png
    - r-rlang
    - r-stringr
    - r-xml2

test:
  commands:
    - $R -e "library('gridtext')"           # [not win]
    - "\"%R%\" -e \"library('gridtext')\""  # [win]

about:
  home: https://wilkelab.org/gridtext
  license: MIT
  summary: Provides support for rendering of formatted text using 'grid' graphics. Text can be formatted via a minimal subset of 'Markdown', 'HTML', and inline 'CSS' directives, and it can be rendered both with and without word wrap.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
